### ISSUE TITLE
Octave_kernel for Jupyter on Windows does not work

### ISSUE THREAD

**Issue by uozden** [dsblank/simple_kernel#6]
Dear @dsblank, sorry for asking your help about a by-product but thought you would help us with this issue since your comment here is valuable ``https://github.com/Calysto/octave_kernel/issues/28``. I am using ``Python 3.5 on Windows 10- 64bit and Octave 4.0.2``. It seems that ``the octave_kernel`` has not been maintained. Thank you for your kind help. Regards

**Comment by dsblank** [comment]
octave_kernel is maintained. But maybe you want to try Linux.

**Comment by uozden** [comment]
Thank you for your response @dsblank . Do you mean installing ``Linux version of octave_kernel`` on Windows would work. It is not clear to me. Regards

**Comment by dsblank** [comment]
There is only one version of octave_kernel. But maybe you want to try Linux as an operating system? It is free (like octave) and doesn't have the limitations of Windows. You can even run the kernel on a virtual Linux machine.
